export const COLORS = {
    lightBack: '#343434',
    lightPurple: '#819ee5',
    white: '#ffffff',
    lightBlue: "#e2edf5",
    lightYellow: "#f0db4f",
    lightPink: "#f4b0ca",
    lightGray: '#e5e6e8',
    lightOrange: '#f76300',
    white: '#fff',
    black: '#000',
    blue: '#5D5FEE',
    grey: '#BABBC3',
    light: '#F3F4FB',
    darkBlue: '#7978B5',
    red: 'red',
}